---
title: "Illusion and Reality of Bloatware: A meme saga"
description: Change your bloat to thicc
date: "2019-04-05"
---
# Illusion and Reality of Bloatware: A meme saga


## The current state of software, and the "community"

Aren't computers great? You might get two different answers depending on whether you're asking a classical user, or someone a bit more "hip", which the classical trolls love to refer as Soyboys in the Tech sense. However, that's not a term I am going to use but I still need to make a distinguish between the two types. So let's come with up two new terms (which are named like this for no particular reason): CoVs (the classical ones), and the nCoVs (the new computer people). The n in this context refers to NodeJS


Examples of CoVs are the kind of people who love C (or lisp), have a 10 year old laptop at the least, and have a strong love or hate for Microsoft. The nCoVs are the web age people, these are the people who love JavaScript, Node, Electron, and other "BLOATED" stuff.


## In the offense of bloat

Before we criticize bloatware, we need to first define bloatware. Bloatware is when a piece of software is often bogged down with unnecessary features or other software, which are strictly "additional" items, and are not part of the core functionality. Bloatware has been around for quite some time, but quite recently there has been a push within the software community (mostly the Free Software community) to move towards the other side of the software, which prides itself in ridding itself of useless features.


These are the developers that have convinced themselves that they are following the [UNIX Philosophy](https://homepage.cs.uri.edu/~thenry/resources/unix_art/ch01s06.html), and it's alright to get rid of the features that could be considered as additional, and yet remain one of the most heavily used. I'm obviously referring to the people behind [Suckless Software](https://suckless.org/), whose software I actually use on a day to day basis (simple terminal, dmenu, and dwm at the time of this writing). However I'm also slightly delusional and have (finally) deemed my time worthy of more than configging and patching up things, so I end up using someone else's patched builds of this software.


Now that I have given a little background on the two different types of software in competition, let's get this straight: I (currently) hold a firm anti bloatware stance. This stance in the meantime, is effectively useless, I'll still continue to use software, however for ideological reasons, I have to denounce the software, and would try to avoid my own software filled with useless things. That said however, I am not opposed to Thiccware (a term that I definitely didn't make up).

## With 2 C's
Thiccware is software which might contain add-on features by default, but those features are used enough, that it validates their existence. Examples of Thiccware include the Brave Browser, a few CADs, VSCode etc. The main reason why anyone should be using any software is to make themselves more productive over all. Minimal Software is often more customizable, and might fit someone else's workflow better. But it's usage is only validated, when the user is able to productive with that software instead of spending all waking times configuring the damn thing.

A lot of minimalists will be angry at me, and accuse me of using bloated software myself, which I might be (hint: Emacs). However next time, before you comment on that Reddit or YouTube thread. Give it some thought. Maybe the software is not bloat, it might just be thicc?

~~ :)

Or it could really be super bloated, bring a `dd` just in case.

Ciao


