---
title: "Choice is an Illusion, and this time it's Linux"
description: Change your bloat to thicc
date: "2019-03-05"
---

# Illusion of Choice: Linux Edition
It's always hard to pinpoint the audience this blog is being written for, but then I end up realizing it's mostly just written for me. However if anyone else happens to come across this. Aces! You get a unicorn, just not from me. Aside from the weak attempt at humor/humour gained from watching too much British telly over this quarantine break, here's some rambling. (Keep reading find the best OS, distro, GUI to work in the most efficient way!)

To follow through this incoherent jumble of thoughts I expect the following from you:
1. A little familiarity with Linux (if you correct me by saying GNU/Linux, or GNU+Linux, I am legally obligated to burn a GNU plushie, so let's not harm little Gnu's shall we?)

2. Ability to search for things on the internet. (much more of a skill than people usually give it credit for)
3. Some time spent that will not benefit in you gaining any tech knowledge

I also recognize a lot of my thoughts will come to look inspired (or reflected) from and by [Luke Smith](https://www.youtube.com/channel/UC2eYFnH61tmytImy1mTYvhA). I do not share his political beliefs, however it would be unfair to say he wasn't the reason I started using Linux full-time, and teaching me about it. That said today I will echo his words "Linux distributions are a social construct", but go a little further down the rabbit hole and talk about why most things people usually take sides on (i.e. Window Managers, text editors, etc.) also are.


## What's inside your Linux box

So here's what usually ends up making a functional Linux box (for the end-user, not a server):
1. Hardware : hah, yes
2. The kernel: This is what "Linux" is, the kernel. It interacts the hardware and the software, pretty important don't ya think?
3. The userspace: This is where YOU come in, and interact with the system.

**So what makes separates a distribution from another?**
1. The Graphical Stuff: This is what births most of these spinoff distributions: Kubuntu, Lubuntu, Mate, which are all Ubuntu, with a different default GUI from regular Ubuntu. I'd be ignorant to say that's all they change, but I am not looking to make friends here, so why not throw in Elementary, Mint and others in too (I know they worked hard on Pantheon, now please let me live).

2. The Runit system: This I respect more. These people knew they wanted a change, and went doing this in the worst way possible. Of course more props to OG distros more than spinoff ones. OG is Void, Gentoo, GUIX(my apologies), and spinoffs are Artix, Devuan, etc. If you think I am gonna comment on SystemD (I know it's not capitalized like that), you're out of your mind.

3. PACKAGE MANAGER: Biggest one: How to install packages? pacman (represent), portage, apt, xbps, etc. Congrats you made yourself unique! Now go and do the same thing which the others do. If you can't, doctors recommend LFS.

4. FSF Reasons: This website is hosted by GitHub (at the time of writing), so why are you here. Shoutouts to Parabola, Trisquel, PureOS,  Hyperbola (no shoutouts to this one), etc.

5. Something Special: This is where something unique comes in, like Nix and guix, and you can't figure out how to install pip packages. (For noobies: Nix is more usable, GUIX is for:___ )


## To hell with ricing
To anger even more of this already segmented Linux community, something I might be a part of (verdict still out). Newbies end up forgetting they are using a COMPUTER to do actual work. I have been in this position, and well have accepted a single thing that (mostly) works out for me (hint using someone else's dots).

You are not to gain anything more from making your system look prettier, and more and more efficient. Just get what you want (quickly), and get to your real work! The amount of man hours I have wasted on delaying my actual work, and then this random rambling should give you some clue. USE IT FOR ACTUAL WORK.

Ricing is for cars, 42 :)

## My point?
Not sure but something along the lines of, if everything you're comparing with each other does the same thing anyways. Just shut up, pick one randomly, GET TO WORK. If you don't like it, pick something else and GET TO WORK.

Ciao? Alvida? whatever you speak

bye